# Generated by Django 3.0.2 on 2021-10-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_formfield_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
